---
abstract: 'DPath is not XPath!'
author:
  - 'Steffen Schwigon, C<< <schwigon at cpan.org> >>'
build_requires:
  Clone: 0
  Devel::Size: 0
  Test::Aggregate::Nested: 0
  Test::Deep: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-DPath
no_index:
  directory:
    - inc
    - t
requires:
  Class::XSAccessor: 0
  Class::XSAccessor::Array: 0
  List::MoreUtils: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  Text::Balanced: 2.02
  aliased: 0
  parent: 0
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
version: 0.34
