---
abstract: 'DPath is not XPath!'
author:
  - 'Steffen Schwigon, C<< <schwigon at cpan.org> >>'
build_requires:
  Clone: 0
  ExtUtils::MakeMaker: 6.42
  Test::Deep: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-DPath
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  List::MoreUtils: 0
  Object::Tiny::RW: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  aliased: 0
  parent: 0
  perl: 5.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.21
