---
abstract: 'DPath is not XPath!'
author:
  - 'Steffen Schwigon, C<< <schwigon at cpan.org> >>'
build_requires:
  Clone: 0
  ExtUtils::MakeMaker: 6.42
  Test::Deep: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-DPath
no_index:
  directory:
    - inc
    - t
requires:
  B::Hooks::EndOfScope: 0.05
  Class::MOP: 0.84
  List::MoreUtils: 0
  Moose: 0.79
  MooseX::Declare: 0.22
  MooseX::Method::Signatures: 0.16
  MooseX::Types::Structured: 0.14
  Parse::Method::Signatures: 1.003005
  Scalar::Util: 0
  Sub::Exporter: 0
  namespace::autoclean: 0.05
  parent: 0
  perl: 5.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.17
