---
abstract: 'DPath is not XPath!'
author:
  - 'Steffen Schwigon, C<< <schwigon at cpan.org> >>'
build_requires:
  Clone: 0
  Devel::Size: 0
  ExtUtils::MakeMaker: 6.42
  Test::Deep: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-DPath
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::XSAccessor: 1.05
  Class::XSAccessor::Array: 0
  Iterator::Util: 0
  List::MoreUtils: 0
  Safe: 2.29
  Scalar::Util: 0
  Sub::Exporter: 0
  Text::Balanced: 2.02
  aliased: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Data-DPath
  license: http://dev.perl.org/licenses/
  repository: git://github.com/renormalist/data-dpath.git
version: 0.44
